# Generated by Django 5.1.4 on 2024-12-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('type', models.IntegerField(choices=[(3, 'Thriller'), (1, 'Sci-Fi'), (0, 'Unnown'), (2, 'Drama'), (4, 'Comedy')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('movie_description', models.TextField(max_length=255)),
                ('premiere', models.BooleanField(default=False)),
                ('premiere_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('additional_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_description', models.TextField(default='', max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.movie')),
            ],
        ),
    ]
