# Generated by Django 5.1.4 on 2024-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='type',
            field=models.IntegerField(choices=[(4, 'Comedy'), (3, 'Thriller'), (0, 'Unnown'), (1, 'Sci-Fi'), (2, 'Drama')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
